DROP DATABASE IF EXISTS phone;
CREATE DATABASE Phone;
USE phone;
CREATE TABLE Best_phones(
id int  AUTO_INCREMENT,
name VARCHAR(150),
Network_technology VARCHAR(150),
Launch_year INTEGER,
Launch_month VARCHAR (150),
Body_dimensions VARCHAR(150),
Body_weight VARCHAR(150),
Body_build VARCHAR(150),
Body_SIM VARCHAR(350),
Display_type VARCHAR(150),
Display_size VARCHAR(150),
Display_resolution VARCHAR(150),
Display_protection VARCHAR(150),
Platform_operating_system  VARCHAR(150),
Platform_chipset  VARCHAR(150),
Platform_central_processing_unit  VARCHAR(150),
Platform_graphics_processing_unit  VARCHAR(150),
Memory_card_slot VARCHAR(150),
Memory_internal VARCHAR(150),
Main_camera VARCHAR(350),
Main_camera_features VARCHAR(150),
Main_camera_video VARCHAR(150),
Selfie_camera VARCHAR(350),
Selfie_camera_features VARCHAR(150),
Selfie_camera_video VARCHAR(150),
Sound_loudspeaker VARCHAR(150),
Sound_jack VARCHAR(150),
Communications_wireless_local_area_network VARCHAR(150),
Communications_bluetooth VARCHAR(150),
Communications_GPS VARCHAR(150),
Communications_NFC VARCHAR(150),
Communications_radio VARCHAR(150),
Communications_USB VARCHAR(150),
Features_sensors VARCHAR(250),
Battery_type VARCHAR(150),
Battery_charging VARCHAR(150),
Miscellaneous_colors VARCHAR(150),
Miscellaneous_models VARCHAR(150),
PRIMARY KEY (ID)
);
INSERT INTO Best_phones (name, Network_technology, Launch_year, Launch_month, Body_dimensions, Body_weight, Body_build, Body_SIM, Display_type, Display_size, Display_resolution, Display_protection, Platform_operating_system, Platform_chipset, Platform_central_processing_unit, Platform_graphics_processing_unit, Memory_card_slot, Memory_internal, Main_camera, Main_camera_features, Main_camera_video, Selfie_camera, Selfie_camera_features, Selfie_camera_video, Sound_loudspeaker, Sound_jack, Communications_wireless_local_area_network, Communications_bluetooth, Communications_GPS, Communications_NFC, Communications_radio, Communications_USB, Features_sensors, Battery_type, Battery_charging, Miscellaneous_colors, Miscellaneous_models )
 VALUES ('Asus ZenFone 7','GSM/HSPA/LTE/5G',2020,'August 26','165.1 x 77.3 x 9.6 mm (6.5 x 3.04 x 0.38 in)','230 g (8.11 oz)','Glass front (Gorilla Glass 6), glass back (Gorilla Glass 3), aluminum frame','Dual SIM (Nano-SIM, dual stand-by)','Super AMOLED, 90Hz, HDR10+, 700 nits (HBM)','6.67 inches, 107.4 cm2 (~84.2% screen-to-body ratio)','1080 x 2400 pixels, 20:9 ratio (~395 ppi density)','Corning Gorilla Glass 6','Android 10, upgradable to Android 11, ZenUI 8','Qualcomm SM8250 Snapdragon 865 5G (7 nm+)','Octa-core (1x2.84 GHz Kryo 585 & 3x2.42 GHz Kryo 585 & 4x1.80 GHz Kryo 585)','Adreno 650','microSDXC (dedicated slot)','128GB 6GB RAM, 128GB 8GB RAM','64 MP, f/1.8, 26mm (wide), 1/1.72", 0.8µm, PDAF 8 MP, f/2.4, 80mm (telephoto), PDAF, 3x optical zoom 12 MP, f/2.2, 113˚, 17mm (ultrawide), 1/2.55", 1.4µm, dual pixel PDAF',
 'Dual-LED flash, HDR, auto panorama (motorized rotation)','8K@30fps, 4K@30/60/120fps, 1080p@30/60/240fps, 720p@480fps; gyro-EIS, HDR','Motorized flip-up main camera module','Dual-LED flash, HDR, auto panorama (motorized rotation)','8K@30fps, 4K@30/60/120fps, 1080p@30/60/240fps, 720p@480fps; gyro-EIS, HDR','Yes, with stereo speakers','No 24-bit/192kHz audio','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot','5.0, A2DP, LE, aptX Adaptive','Yes, with dual-band A-GPS, GLONASS, GALILEO, BDS, QZSS, NavIC','yes','no','USB type-C','Fingerprint (side-mounted), accelerometer, gyro, proximity, compass','Li-Po 5000 mAh, non-removable','Fast charging 30W, 60% in 34 min, 100% in 93 min (advertised) USB Power Delivery 3.0 Reverse charging','Aurora Black, Pastel White','ZS670KS, ASUS_I002D, I002D');
 INSERT INTO Best_phones (name, Network_technology, Launch_year, Launch_month, Body_dimensions, Body_weight, Body_build, Body_SIM, Display_type, Display_size, Display_resolution, Display_protection, Platform_operating_system, Platform_chipset, Platform_central_processing_unit, Platform_graphics_processing_unit, Memory_card_slot, Memory_internal, Main_camera, Main_camera_features, Main_camera_video, Selfie_camera, Selfie_camera_features, Selfie_camera_video, Sound_loudspeaker, Sound_jack, Communications_wireless_local_area_network, Communications_bluetooth, Communications_GPS, Communications_NFC, Communications_radio, Communications_USB, Features_sensors, Battery_type, Battery_charging, Miscellaneous_colors, Miscellaneous_models )
 VALUES ('Honor 30','GSM/HSPA/LTE/5G',2020,'August 15','160.3 x 74.2 x 8.1 mm (6.31 x 2.92 x 0.32 in)','185 g (6.53 oz)','null','Hybrid Dual SIM (Nano-SIM, dual stand-by)','OLED','6.53 inches, 102.9 cm2 (~86.6% screen-to-body ratio)','1080 x 2400 pixels, 20:9 ratio (~403 ppi density)','null','Android 10, Magic UI 3, no Google Play Services','Kirin 985 5G (7 nm)','Octa-core (1x2.58 GHz Cortex-A76 & 3x2.40 GHz Cortex-A76 & 4x1.84 GHz Cortex-A55)','Mali-G77','NM (Nano Memory), up to 256GB (uses shared SIM slot)','128GB 6GB RAM, 128GB 8GB RAM, 256GB 8GB RAM UFS','40 MP, f/1.8, 27mm (wide), 1/1.7", PDAF 8 MP, f/3.4, 125mm (Periscope telephoto), PDAF, OIS, 5x optical zoom 8 MP, f/2.4, 17mm (ultrawide) 2 MP, (depth) ','LED flash, panorama, HDR',
 '4K@30/60fps, 1080p@30/60fps, 720p@960fps; gyro-EIS','32 MP, f/2.0, 26mm (wide), 1/2.8", 0.8µm','HDR','4K, 1080p; gyro-EIS','Yes','No','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot','5.1, A2DP, LE','Yes, with dual-band A-GPS, GLONASS, GALILEO, BDS, QZSS, NavIC','yes','no','USB Type-C 2.0, USB On-The-Go','Fingerprint (under display, optical), accelerometer, gyro, proximity, compass','Li-Po 4000 mAh, non-removable','Fast charging 40W Reverse charging 5W','Titanium silver, Emerald Green, Midnight Black, Icelandic Frost, Neon purple','BMH-AN10');
INSERT INTO Best_phones (name, Network_technology, Launch_year, Launch_month, Body_dimensions, Body_weight, Body_build, Body_SIM, Display_type, Display_size, Display_resolution, Display_protection, Platform_operating_system, Platform_chipset, Platform_central_processing_unit, Platform_graphics_processing_unit, Memory_card_slot, Memory_internal, Main_camera, Main_camera_features, Main_camera_video, Selfie_camera, Selfie_camera_features, Selfie_camera_video, Sound_loudspeaker, Sound_jack, Communications_wireless_local_area_network, Communications_bluetooth, Communications_GPS, Communications_NFC, Communications_radio, Communications_USB, Features_sensors, Battery_type, Battery_charging, Miscellaneous_colors, Miscellaneous_models )
 VALUES ('Huawei Mate 40','GSM/HSPA/LTE/5G',2020,'October 22','158.6 x 72.5 x 8.8 mm (Glass) / 9.2mm (Leather)','188 g (Glass) / 184 g (Leather) (6.49 oz)','Glass front, glass back or eco leather back, aluminum frame','Single SIM (Nano-SIM) or Hybrid Dual SIM (Nano-SIM, dual stand-by) IP53, dust and splash protection','OLED, HDR10, 90Hz','6.5 inches, 102.7 cm2 (~89.3% screen-to-body ratio)','1080 x 2376 pixels (~402 ppi density)','null','Android 10, EMUI 11, no Google Play Services','Kirin 9000E 5G (5 nm)','Octa-core (1x3.13 GHz Cortex-A77 & 3x2.54 GHz Cortex-A77 & 4x2.05 GHz Cortex-A55)','Mali-G78 MP22','NM (Nano Memory), up to 256GB (uses shared SIM slot)','128GB 8GB RAM, 256GB 8GB RAM UFS 3.1','50 MP, f/1.9, 23mm (wide), 1/1.28", 1.22µm, omnidirectional PDAF, Laser AF
8 MP, f/2.4, 85mm (telephoto), PDAF, OIS, 3x optical zoom 16 MP, f/2.2, 17mm (ultrawide)','Leica optics, LED flash, panorama, HDR','4K@30/60fps, 1080p@30/60/120/240fps, 1080p@960fps, gyro-EIS','13 MP, f/2.4, 18mm (ultrawide)','HDR, panorama','4K@30/60fps, 1080p@30/60/240fps','Yes','Yes 32-bit/384kHz audio','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot','5.2, A2DP, LE','Yes, with dual-band A-GPS, GLONASS, GALILEO, BDS, QZSS, NavIC','yes','no','USB Type-C 3.1, USB On-The-Go','Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, color spectrum','Li-Po 4200 mAh, non-removable','Fast charging 40W Fast wireless charging 40W Reverse charging 5W','Silver, White, Black, Green, Yellow','OCE-AN10');
 INSERT INTO Best_phones (name, Network_technology, Launch_year, Launch_month, Body_dimensions, Body_weight, Body_build, Body_SIM, Display_type, Display_size, Display_resolution, Display_protection, Platform_operating_system, Platform_chipset, Platform_central_processing_unit, Platform_graphics_processing_unit, Memory_card_slot, Memory_internal, Main_camera, Main_camera_features, Main_camera_video, Selfie_camera, Selfie_camera_features, Selfie_camera_video, Sound_loudspeaker, Sound_jack, Communications_wireless_local_area_network, Communications_bluetooth, Communications_GPS, Communications_NFC, Communications_radio, Communications_USB, Features_sensors, Battery_type, Battery_charging, Miscellaneous_colors, Miscellaneous_models )
 VALUES ('Huawei nova 7 5G','GSM/CDMA/HSPA/LTE/5G',2020,'April 23','160.6 x 74.3 x 8 mm (6.32 x 2.93 x 0.31 in)','180 g (6.35 oz)','null','Single SIM (Nano-SIM) or Dual SIM (Nano-SIM, dual stand-by)','OLED','6.53 inches, 102.9 cm2 (~86.3% screen-to-body ratio)','1080 x 2400 pixels, 20:9 ratio (~403 ppi density)','null','Android 10, EMUI 10.1, no Google Play Services','Kirin 985 5G (7 nm)','Octa-core (1x2.58 GHz Cortex-A76 & 3x2.40 GHz Cortex-A76 & 4x1.84 GHz Cortex-A55)','Mali-G77','No','128GB 6GB RAM, 128GB 8GB RAM, 256GB 8GB RAM UFS 3.0','64 MP, f/1.8, 26mm (wide), PDAF 8 MP, f/2.4, 80mm (telephoto), PDAF, 3x optical zoom 8 MP, f/2.4, 17mm (ultrawide) 2 MP, f/2.4, (macro)
 ','LED flash, panorama, HDR','4K, 1080p, 720p@960fps, gyro-EIS','32 MP, f/2.2, 26mm (wide), 1/2.8", 0.8µm','HDR','4K','Yes','No','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot','5.1, A2DP, LE','Yes, with A-GPS, GLONASS, GALILEO, BDS, QZSS','yes','no','USB Type-C 2.0, USB On-The-Go','Fingerprint (under display, optical), accelerometer, gyro, proximity, compass','Li-Po 4000 mAh, non-removable','Fast charging 40W, 75% in 30 min (advertised) Reverse charging 5W','Black, Space Silver, Midsummer Purple, Red, Green','JEF-AN00, JEF-NX9, JEF-AN20');
INSERT INTO Best_phones (name, Network_technology, Launch_year, Launch_month, Body_dimensions, Body_weight, Body_build, Body_SIM, Display_type, Display_size, Display_resolution, Display_protection, Platform_operating_system, Platform_chipset, Platform_central_processing_unit, Platform_graphics_processing_unit, Memory_card_slot, Memory_internal, Main_camera, Main_camera_features, Main_camera_video, Selfie_camera, Selfie_camera_features, Selfie_camera_video, Sound_loudspeaker, Sound_jack, Communications_wireless_local_area_network, Communications_bluetooth, Communications_GPS, Communications_NFC, Communications_radio, Communications_USB, Features_sensors, Battery_type, Battery_charging, Miscellaneous_colors, Miscellaneous_models )
 VALUES ('Huawei nova 7i','GSM/CDMA/HSPA/LTE',2020,'January 30','159.2 x 76.3 x 8.7 mm (6.27 x 3.00 x 0.34 in)','183 g (6.46 oz)','Glass front, plastic back, plastic frame','Single SIM (Nano-SIM) or Hybrid Dual SIM (Nano-SIM, dual stand-by)','LTPS IPS LCD','6.4 inches, 101.4 cm2 (~83.5% screen-to-body ratio)','1080 x 2310 pixels (~398 ppi density)','null','Android 10, EMUI 10, no Google Play Services','Kirin 810 (7 nm)','Octa-core (2x2.27 GHz Cortex-A76 & 6x1.88 GHz Cortex-A55)','Mali-G52 MP6','NM (Nano Memory), up to 256GB (uses shared SIM slot)',' 128GB 8GB RAM UFS 2.1','48 MP, f/1.8, 26mm (wide), 1/2.0", 0.8µm, PDAF 8 MP, f/2.4, (ultrawide) 2 MP, f/2.4, (macro) 2 MP, f/2.4, (depth)',
 'LED flash, HDR, panorama','1080p@30fps','	16 MP, f/2.0, (wide), 1/3.06", 1.0µm','HDR','1080p@30fps','Yes','Yes','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot','5.1, A2DP, LE','Yes, with A-GPS, GLONASS, GALILEO, BDS, QZSS','no','FM radio (market/region dependent)','USB Type-C 2.0, USB On-The-Go','Fingerprint (side-mounted), accelerometer, gyro, proximity, compass','Li-Po 4200 mAh, non-removable','Fast charging 40W, 70% in 30 min (advertised)','Midnight Black, Crush Green, Sakura Pink','JNY-L22B, JNY-L21A, JNY-L01A, JNY-L21B, JNY-L22A, JNY-L02A, JNY-LX2');
 INSERT INTO Best_phones (name, Network_technology, Launch_year, Launch_month, Body_dimensions, Body_weight, Body_build, Body_SIM, Display_type, Display_size, Display_resolution, Display_protection, Platform_operating_system, Platform_chipset, Platform_central_processing_unit, Platform_graphics_processing_unit, Memory_card_slot, Memory_internal, Main_camera, Main_camera_features, Main_camera_video, Selfie_camera, Selfie_camera_features, Selfie_camera_video, Sound_loudspeaker, Sound_jack, Communications_wireless_local_area_network, Communications_bluetooth, Communications_GPS, Communications_NFC, Communications_radio, Communications_USB, Features_sensors, Battery_type, Battery_charging, Miscellaneous_colors, Miscellaneous_models )
 VALUES ('Huawei P40','GSM/HSPA/LTE',2020,'April 06','173.4 x 79 x 8.8 mm (6.83 x 3.11 x 0.35 in)','206 g (7.27 oz)','null','Dual SIM (Nano-SIM, dual stand-by)','IPS LCD','6.95 inches, 114.7 cm2 (~83.7% screen-to-body ratio)','720 x 1640 pixels (~258 ppi density)','Corning Gorilla Glass','Android 10, XOS 6.0','Mediatek Helio G70 (12 nm)','Octa-core (2x2.0 GHz Cortex-A75 & 6x1.7 GHz Cortex-A55)','Mali-G52 2EEMC2','microSDXC (dedicated slot)','64GB 4GB RAM, 128GB 4GB RAM, 128GB 6GB RAM eMMC 5.1','48 MP, f/1.8, (wide), 1/2.0", 0.8µm, PDAF 2 MP, f/2.4, (macro) 2 MP, f/2.4, (depth) 2 MP, f/1.8, (dedicated video camera) - 128/6 model only','Quad-LED flash, panorama, HDR','1080p@30fps','16 MP, f/2.0, 26mm (wide), 1/3.06", 1.0µm','null',
 '1080p@30fps','Yes, with dual speakers','Yes','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot','5.0, A2DP, LE','Yes, with A-GPS','No','FM radio','USB 2.0, USB On-The-Go','Fingerprint (side-mounted), accelerometer, proximity, compass','Li-Po 5000 mAh, non-removable','Fast charging 18W','Forest Green, Aether Black, Bolivia Blue','X690B, X690');
INSERT INTO Best_phones (name, Network_technology, Launch_year, Launch_month, Body_dimensions, Body_weight, Body_build, Body_SIM, Display_type, Display_size, Display_resolution, Display_protection, Platform_operating_system, Platform_chipset, Platform_central_processing_unit, Platform_graphics_processing_unit, Memory_card_slot, Memory_internal, Main_camera, Main_camera_features, Main_camera_video, Selfie_camera, Selfie_camera_features, Selfie_camera_video, Sound_loudspeaker, Sound_jack, Communications_wireless_local_area_network, Communications_bluetooth, Communications_GPS, Communications_NFC, Communications_radio, Communications_USB, Features_sensors, Battery_type, Battery_charging, Miscellaneous_colors, Miscellaneous_models )
 VALUES ('Iphone 12','GSM/CDMA/HSPA/EDVO/LTE/5G',2020,'October 13','146.7 x 71.5 x 7.4 mm (5.78 x 2.81 x 0.29 in)','164 g (5.78 oz)','Glass front (Gorilla Glass), glass back (Gorilla Glass), aluminum frame','Single SIM (Nano-SIM and/or eSIM) or Dual SIM (Nano-SIM, dual stand-by) - for China IP68 dust/water resistant (up to 6m for 30 mins) Apple Pay (Visa, MasterCard, AMEX certified)','Super Retina XDR OLED, HDR10, Dolby Vision, 625 nits (typ), 1200 nits (peak)','6.1 inches, 90.2 cm2 (~86.0% screen-to-body ratio)','1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density)',' Scratch-resistant ceramic glass, oleophobic coating Wide color gamut True-tone','iOS 14.1, upgradable to iOS 14.7','Apple A14 Bionic (5 nm)',
 'Hexa-core (2x3.1 GHz Firestorm + 4x1.8 GHz Icestorm)','Apple GPU (4-core graphics)','No',' 64GB 4GB RAM, 128GB 4GB RAM, 256GB 4GB RAM NVMe','12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS 12 MP, f/2.4, 120˚, 13mm (ultrawide), 1/3.6"','Dual-LED dual-tone flash, HDR (photo/panorama)','4K@24/30/60fps, 1080p@30/60/120/240fps, HDR, Dolby Vision HDR (up to 30fps), stereo sound rec','	12 MP, f/2.2, 23mm (wide), 1/3.6" SL 3D, (depth/biometrics sensor)','HDR','4K@24/30/60fps, 1080p@30/60/120fps, gyro-EIS','Yes, with stereo speakers','No','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot','5.0, A2DP, LE','Yes, with A-GPS, GLONASS, GALILEO, BDS, QZSS','Yes','No','Lightning, USB 2.0',
 'Face ID, accelerometer, gyro, proximity, compass, barometer Siri natural language commands and dictation Ultra Wideband (UWB) support','Li-Ion 2815 mAh, non-removable (10.78 Wh)','Fast charging 20W, 50% in 30 min (advertised) USB Power Delivery 2.0 Qi magnetic fast wireless charging 15W','Black, White, Red, Green, Blue, Purple','A2403, A2172, A2402, A2404, iPhone13,2');
 
 INSERT INTO Best_phones (name, Network_technology, Launch_year, Launch_month, Body_dimensions, Body_weight, Body_build, Body_SIM, Display_type, Display_size, Display_resolution, Display_protection, Platform_operating_system, Platform_chipset, Platform_central_processing_unit, Platform_graphics_processing_unit, Memory_card_slot, Memory_internal, Main_camera, Main_camera_features, Main_camera_video, Selfie_camera, Selfie_camera_features, Selfie_camera_video, Sound_loudspeaker, Sound_jack, Communications_wireless_local_area_network, Communications_bluetooth, Communications_GPS, Communications_NFC, Communications_radio, Communications_USB, Features_sensors, Battery_type, Battery_charging, Miscellaneous_colors, Miscellaneous_models )
 VALUES ('Iphone 12 Pro','GSM/CDMA/HSPA/EDVO/LTE/5G',2020,'October 13','146.7 x 71.5 x 7.4 mm (5.78 x 2.81 x 0.29 in)','189 g (6.67 oz)','Glass front (Gorilla Glass), glass back (Gorilla Glass), stainless steel frame','Single SIM (Nano-SIM and/or eSIM) or Dual SIM (Nano-SIM, dual stand-by) - for China IP68 dust/water resistant (up to 6m for 30 mins) Apple Pay (Visa, MasterCard, AMEX certified)','Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (typ), 1200 nits (peak)','6.1 inches, 90.2 cm2 (~86.0% screen-to-body ratio)','1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density)',' Scratch-resistant ceramic glass, oleophobic coating Wide color gamut True-tone','iOS 14.1, upgradable to iOS 14.7','Apple A14 Bionic (5 nm)',
 'Hexa-core (2x3.1 GHz Firestorm + 4x1.8 GHz Icestorm)','Apple GPU (4-core graphics)','No',' 128GB 6GB RAM, 256GB 6GB RAM, 512GB 6GB RAM NVMe','12 MP, f/1.6, 26mm (wide), 1.4µm, dual pixel PDAF, OIS 12 MP, f/2.0, 52mm (telephoto), 1/3.4", 1.0µm, PDAF, OIS, 2x optical zoom 12 MP, f/2.4, 120˚, 13mm (ultrawide), 1/3.6" TOF 3D LiDAR scanner (depth)','Dual-LED dual-tone flash, HDR (photo/panorama)','4K@24/30/60fps, 1080p@30/60/120/240fps, HDR, Dolby Vision HDR (up to 30fps), stereo sound rec','	12 MP, f/2.2, 23mm (wide), 1/3.6" SL 3D, (depth/biometrics sensor)','HDR','4K@24/30/60fps, 1080p@30/60/120fps, gyro-EIS','Yes, with stereo speakers','No','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot','5.0, A2DP, LE','Yes, with A-GPS, GLONASS, GALILEO, BDS, QZSS','Yes','No','Lightning, USB 2.0',
 'Face ID, accelerometer, gyro, proximity, compass, barometer Siri natural language commands and dictation Ultra Wideband (UWB) support','Li-Ion 2815 mAh, non-removable (10.78 Wh)','Fast charging 20W, 50% in 30 min (advertised) USB Power Delivery 2.0 Qi magnetic fast wireless charging 15W','Silver, Graphite, Gold, Pacific Blue','A2407, A2341, A2406, A2408, iPhone13,3');
 INSERT INTO Best_phones (name, Network_technology, Launch_year, Launch_month, Body_dimensions, Body_weight, Body_build, Body_SIM, Display_type, Display_size, Display_resolution, Display_protection, Platform_operating_system, Platform_chipset, Platform_central_processing_unit, Platform_graphics_processing_unit, Memory_card_slot, Memory_internal, Main_camera, Main_camera_features, Main_camera_video, Selfie_camera, Selfie_camera_features, Selfie_camera_video, Sound_loudspeaker, Sound_jack, Communications_wireless_local_area_network, Communications_bluetooth, Communications_GPS, Communications_NFC, Communications_radio, Communications_USB, Features_sensors, Battery_type, Battery_charging, Miscellaneous_colors, Miscellaneous_models )
 VALUES ('Iphone SE (2020)','GSM/CDMA/HSPA/EDVO/LTE',2020,'April 15','138.4 x 67.3 x 7.3 mm (5.45 x 2.65 x 0.29 in)','148 g (5.22 oz)','Glass front, glass back, aluminum frame','Nano-SIM and/or eSIM IP67 dust/water resistant (up to 1m for 30 mins) Apple Pay (Visa, MasterCard, AMEX certified)','Retina IPS LCD, 625 nits (typ)','4.7 inches, 60.9 cm2 (~65.4% screen-to-body ratio)','750 x 1334 pixels, 16:9 ratio (~326 ppi density)',' Ion-strengthened glass, oleophobic coating Wide color gamut True-tone','iOS 13, upgradable to iOS 14.7','Apple A13 Bionic (7 nm+)',
 'Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder)','Apple GPU (4-core graphics)','No',' 64GB 3GB RAM, 128GB 3GB RAM, 256GB 3GB RAM NVMe','12 MP, f/1.8 (wide), PDAF, OIS','Quad-LED dual-tone flash, HDR, panorama','4K@24/30/60fps, 1080p@30/60/120/240fps, HDR, Dolby Vision HDR (up to 30fps), stereo sound rec','	7 MP, f/2.2','HDR','1080p@30fps; gyro-EIS','Yes, with stereo speakers','No','Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct, hotspot','5.0, A2DP, LE','Yes, with A-GPS, GLONASS','Yes','No','Lightning, USB 2.0',
 'Fingerprint (front-mounted), accelerometer, gyro, proximity, compass, barometer Siri natural language commands and dictation Ultra Wideband (UWB) support','Li-Ion 1821 mAh, non-removable (6.96 Wh)','Fast charging 18W, 50% in 30 min (advertised) Qi wireless charging','Black, White, Red','A2275, A2296, A2298, iPhone12,8');

 
 SELECT * FROM Best_phones;